FROM python

RUN git clone https://github.com/sp2ong/HBmonitor.git \
&& pip install --no-cache-dir -r HBmonitor/requirements.txt \
&& chmod +x HBmonitor/monitor.py \
&& mkdir /var/log/link \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt/HBmonitor
EXPOSE 8080
EXPOSE 9000

CMD /opt/HBmonitor/monitor.py
